apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-application
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'git@github.com:HaPhanBaoMinh/blog_002.git'
        revision: main
        directories:
          - path: dev
          - path: test
          - path: prod
  template:
    metadata:
      name: '{{ .path.basename }}'                 
      labels:
        tier: '{{ .path.basename }}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd                          # because child is an Application manifest
      source:
        repoURL: 'git@github.com:HaPhanBaoMinh/blog_002.git'
        targetRevision: main
        path: '{{ .path.path }}'                   # apps/hight or apps/low
        directory:
          recurse: true # Read all files in the directory
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

