apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-prod
  namespace: argocd   
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes/examples.git
    targetRevision: master
    path: guestbook-go/guestbook-ui   

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true        
      selfHeal: true    


